export const backendRoutes = {
  root: () => '/',
  health: {
    root: () => '/health',
    db: () => '/health/db',
  },
  agents: {
    list: () => '/agents',
    create: () => '/agents',
    byId: (agentId: string) => `/agents/${agentId}`,
    executions: (agentId: string) => `/agents/${agentId}/executions`,
  },
  conversations: {
    list: () => '/conversations',
    create: () => '/conversations',
    mainAgent: () => '/conversations/main-agent-profile',
    updateMainAgent: () => '/conversations/main-agent-profile',
    byId: (conversationId: string) => `/conversations/${conversationId}`,
    messages: (conversationId: string) => `/conversations/${conversationId}/messages`,
    stream: (conversationId: string) => `/conversations/${conversationId}/stream`,
    approvalRequests: (conversationId: string) =>
      `/conversations/${conversationId}/approval-requests`,
    approveApprovalRequest: (approvalRequestId: string) =>
      `/conversations/approval-requests/${approvalRequestId}/approve`,
    rejectApprovalRequest: (approvalRequestId: string) =>
      `/conversations/approval-requests/${approvalRequestId}/reject`,
    requestChangesToApprovalRequest: (approvalRequestId: string) =>
      `/conversations/approval-requests/${approvalRequestId}/request-changes`,
    splitApprovalRequest: (approvalRequestId: string) =>
      `/conversations/approval-requests/${approvalRequestId}/split`,
  },
  tools: {
    list: () => '/tools',
    create: () => '/tools',
    byId: (toolId: string) => `/tools/${toolId}`,
    validate: () => '/tools/validate',
    test: (toolId: string) => `/tools/${toolId}/test`,
    contracts: () => '/tools/contracts',
    contractByName: (toolName: string) => `/tools/contracts/${toolName}`,
    run: (toolName: string) => `/tools/${toolName}/run`,
  },
  modelProviders: {
    list: () => '/model-providers',
    create: () => '/model-providers',
    byId: (providerId: string) => `/model-providers/${providerId}`,
    health: (providerId: string) => `/model-providers/${providerId}/health`,
    test: (providerId: string) => `/model-providers/${providerId}/test`,
    models: (providerId: string) => `/model-providers/${providerId}/models`,
    authorize: (providerId: string) => `/model-providers/${providerId}/authorize`,
    callbackComplete: (providerId: string) => `/model-providers/${providerId}/callback-complete`,
    deviceAuthorize: (providerId: string) => `/model-providers/${providerId}/device-authorize`,
    deviceComplete: (providerId: string) => `/model-providers/${providerId}/device-complete`,
  },
  modelProfiles: {
    list: () => '/model-profiles',
    create: () => '/model-profiles',
    byId: (profileId: string) => `/model-profiles/${profileId}`,
    health: (profileId: string) => `/model-profiles/${profileId}/health`,
    test: (profileId: string) => `/model-profiles/${profileId}/test`,
  },
  documents: {
    ingest: () => '/documents/ingest',
  },
  mcpServers: {
    list: () => '/mcp-servers',
    create: () => '/mcp-servers',
    byId: (serverId: string) => `/mcp-servers/${serverId}`,
    discover: () => '/mcp-servers/discover',
  },
  runtimeAdapters: {
    list: () => '/runtime-adapters',
    create: () => '/runtime-adapters',
    byId: (adapterId: string) => `/runtime-adapters/${adapterId}`,
  },
  connectorRegistry: {
    categories: () => '/integrations/categories',
    capabilities: () => '/integrations/connectors/capabilities',
  },
  connectors: {
    test: (credentialId: string) => `/integrations/connectors/${credentialId}/test`,
  },
  workflows: {
    list: () => '/workflows',
    create: () => '/workflows',
    byId: (workflowId: string) => `/workflows/${workflowId}`,
    sharedMemory: (workflowId: string) => `/workflows/${workflowId}/shared-memory`,
    monitoring: (workflowId: string) => `/workflows/${workflowId}/monitoring`,
    monitoringEvents: (workflowId: string) => `/workflows/${workflowId}/monitoring/events`,
    executions: (workflowId: string) => `/workflows/${workflowId}/executions`,
    startExecution: (workflowId: string) => `/workflows/${workflowId}/executions/start`,
    publish: (workflowId: string) => `/workflows/${workflowId}/publish`,
    unpublish: (workflowId: string) => `/workflows/${workflowId}/unpublish`,
    clone: (workflowId: string) => `/workflows/${workflowId}/clone`,
    validate: () => '/workflows/validate',
  },
  executions: {
    list: () => '/executions',
    active: () => '/executions/active',
    runtimeRevisions: () => '/executions/runtime/revisions',
    runtimeRevisionById: (revisionId: string) => `/executions/runtime/revisions/${revisionId}`,
    runtimeContainers: () => '/executions/runtime/containers',
    runtimeMetrics: () => '/executions/runtime/metrics',
    runtimeContainerLogs: (containerId: string) =>
      `/executions/runtime/containers/${containerId}/logs`,
    runtimeReconcile: () => '/executions/runtime/reconcile',
    create: () => '/executions',
    byId: (executionId: string) => `/executions/${executionId}`,
    start: (executionId: string) => `/executions/${executionId}/start`,
    pause: (executionId: string) => `/executions/${executionId}/pause`,
    resume: (executionId: string) => `/executions/${executionId}/resume`,
    cancel: (executionId: string) => `/executions/${executionId}/cancel`,
    approve: (executionId: string) => `/executions/${executionId}/approve`,
    reject: (executionId: string) => `/executions/${executionId}/reject`,
    events: (executionId: string) => `/executions/${executionId}/events`,
    artifacts: (executionId: string) => `/executions/${executionId}/artifacts`,
    artifactImagesStream: (executionId: string) =>
      `/executions/${executionId}/artifacts/images/stream`,
    hitlStream: (executionId: string) => `/executions/${executionId}/hitl/stream`,
    hitlReply: (executionId: string) => `/executions/${executionId}/hitl/reply`,
    runtimeLogs: (executionId: string) => `/executions/${executionId}/runtime/logs`,
    stream: (executionId: string) => `/executions/${executionId}/stream`,
  },
  storage: {
    presigned: () => '/storage/presigned',
  },
  schedules: {
    list: () => '/schedules',
    create: () => '/schedules',
    byId: (scheduleId: string) => `/schedules/${scheduleId}`,
    enable: (scheduleId: string) => `/schedules/${scheduleId}/enable`,
    disable: (scheduleId: string) => `/schedules/${scheduleId}/disable`,
    triggerNow: (scheduleId: string) => `/schedules/${scheduleId}/trigger-now`,
  },
  observability: {
    executionTimeline: (executionId: string) => `/observability/executions/${executionId}/timeline`,
    agentMetrics: (agentId: string) => `/observability/agents/${agentId}/metrics`,
    workflowMetrics: (workflowId: string) => `/observability/workflows/${workflowId}/metrics`,
    modelUsage: () => '/observability/models/usage',
  },
  profile: {
    credentials: () => '/credentials',
    connectorCredentialSchema: (providerKey: string) =>
      `/credentials/connectors/${providerKey}/schema`,
    validateConnectorCredential: (providerKey: string) =>
      `/credentials/connectors/${providerKey}/validate`,
    createConnectorCredential: (providerKey: string) => `/credentials/connectors/${providerKey}`,
    credentialById: (credentialId: string) => `/credentials/${credentialId}`,
    updateConnectorCredential: (credentialId: string) => `/credentials/${credentialId}/connector`,
    revokeCredential: (credentialId: string) => `/credentials/${credentialId}/revoke`,
    rotateCredential: (credentialId: string) => `/credentials/${credentialId}/rotate`,
  },
  a2a: {
    agentCard: () => '/.well-known/agent-card.json',
    createTask: () => '/a2a/tasks',
    taskById: (taskId: string) => `/a2a/tasks/${taskId}`,
    taskMessages: (taskId: string) => `/a2a/tasks/${taskId}/messages`,
    taskArtifacts: (taskId: string) => `/a2a/tasks/${taskId}/artifacts`,
  },
} as const;
