export const queryKeys = {
  backendAgents: () => ['backendAgents'] as const,
  backendMainAgent: () => ['backendMainAgent'] as const,
  backendAgentRuns: () => ['backendAgentRuns'] as const,
  backendWorkflowList: () => ['backendWorkflowList'] as const,
  backendWorkflow: (workflowId: string) => ['backendWorkflow', workflowId] as const,
  backendWorkflowMonitoringEvents: (workflowId: string) =>
    ['backendWorkflowMonitoringEvents', workflowId] as const,
  backendWorkflowSharedMemory: (workflowId: string) =>
    ['backendWorkflowSharedMemory', workflowId] as const,
  backendWorkflowRuns: (workflowId: string) => ['backendWorkflowRuns', workflowId] as const,
  backendWorkflowSchedules: (workflowId: string) => ['backendSchedules', workflowId] as const,
  backendRuntimeAdapters: () => ['backendRuntimeAdapters'] as const,
  backendBehaviorProfiles: () => ['backendBehaviorProfiles'] as const,
  backendIntegrations: () => ['backendIntegrations'] as const,
  backendRun: (runId: string) => ['backendRun', runId] as const,
  backendRunSession: (runId: string) => ['backendRunSession', runId] as const,
  backendRunEvents: (runId: string) => ['backendRunEvents', runId] as const,
  backendRunTimeline: (runId: string) => ['backendRunTimeline', runId] as const,
  backendRunLogs: (runId: string) => ['backendRunLogs', runId] as const,
  backendRunConversation: (runId: string) => ['backendRunConversation', runId] as const,
  backendActiveRunSessions: () => ['backendActiveRunSessions'] as const,
  toolContracts: () => ['toolContracts'] as const,
  toolContract: (toolName: string) => ['toolContract', toolName] as const,
  tools: () => ['tools'] as const,
} as const;
